<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<div class="private-data-consent">
    <section>img here</section>
    <section>
        <?= $escaper->escapeHtml(__('Your data is collected by us for the sole purpose of providing you with' .
            ' a quality service as expected when you create an account on our site.')) ?>
    </section>
</div>
